#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use Getopt::Long;

binmode(STDOUT, ":utf8");

# Default values
my $optimus_cmd = "optimus-manager --status";
my $gpu_info = "";

sub help {
    print "Usage: get_gpu_info.pl [--command <command>]\n";
    print "--command <command>: The command to get GPU information\n";
    exit 0;
}

GetOptions(
    "help|h" => \&help,
    "command=s" => \$optimus_cmd
);

sub get_gpu_info {
    my $cmd_output = `$optimus_cmd`;
    return $cmd_output;
}

$gpu_info = get_gpu_info();

# Extract GPU information after "Current GPU mode:"
if ($gpu_info =~ /Current GPU mode :\s*(\S+)/) {
    my $gpu_mode = $1;
    print "$gpu_mode\n";
} else {
    print "GPU information not found.\n";
}
